export default function menuPage() {
  const website = document.querySelector(`#content`);
  const contentBox = document.createElement("div");
  contentBox.classList.add("contentBox");
  website.appendChild(contentBox);
  const name = document.createElement("h1");
  name.classList.add("name");
  name.textContent = "Something Fishy";
  contentBox.appendChild(name);
  const homePage = document.createElement("BUTTON");
  homePage.classList.add("homePage");
  homePage.textContent = "Home";
  contentBox.appendChild(homePage);
  const menu = document.createElement("BUTTON");
  menu.classList.add("menu");
  menu.textContent = "Menu";
  contentBox.appendChild(menu);
  const about = document.createElement("BUTTON");
  about.classList.add("about");
  about.textContent = "About";
  contentBox.appendChild(about);
  const contact = document.createElement("BUTTON");
  contact.classList.add("contact");
  contact.textContent = "Contact";
  contentBox.appendChild(contact);

  const menuList = document.createElement("div");
  menuList.classList.add("menuList");
  contentBox.appendChild(menuList);
  const menuHeader = document.createElement("h2");
  menuHeader.classList.add("menuHeader");
  menuHeader.textContent = "Menu";
  menuList.appendChild(menuHeader);
  const title1 = document.createElement("h3");
  title1.classList.add("title1");
  title1.textContent = "Sashimi";
  menuList.appendChild(title1);
  const item1 = document.createElement("div");
  item1.classList.add("item1");
  menuList.appendChild(item1);
  const item1Title = document.createElement("h4");
  item1Title.classList.add("item1Title");
  item1Title.textContent = "Salmon";
  item1.appendChild(item1Title);
  const item1Desc = document.createElement("p");
  item1Desc.classList.add("item1Desc");
  item1Desc.textContent = "Four fresh pieces of salmon, uncooked obviously.";
  item1.appendChild(item1Desc);
  const item1Price = document.createElement("p");
  item1Price.classList.add("item1Price");
  item1Price.textContent = "$3.50";
  item1.appendChild(item1Price);
  const item2 = document.createElement("div");
  item2.classList.add("item2");
  menuList.appendChild(item2);
  const item2Title = document.createElement("h4");
  item2Title.classList.add("item2Title");
  item2Title.textContent = "Fatty Tuna";
  item2.appendChild(item2Title);
  const item2Desc = document.createElement("p");
  item2Desc.classList.add("item2Desc");
  item2Desc.textContent =
    "Four fresh pieces of fatty tuna, more fat means more delicious.";
  item2.appendChild(item2Desc);
  const item2Price = document.createElement("p");
  item2Price.classList.add("item2Price");
  item2Price.textContent = "$5.50";
  item2.appendChild(item2Price);
  const item3 = document.createElement("div");
  item3.classList.add("item3");
  menuList.appendChild(item3);
  const item3Title = document.createElement("h4");
  item3Title.classList.add("item3Title");
  item3Title.textContent = "Yellowtail";
  item3.appendChild(item3Title);
  const item3Desc = document.createElement("p");
  item3Desc.classList.add("item3Desc");
  item3Desc.textContent =
    "Four fresh pieces of yellowtail, sushi for beginners.";
  item3.appendChild(item3Desc);
  const item3Price = document.createElement("p");
  item3Price.classList.add("item3Price");
  item3Price.textContent = "$4.50";
  item3.appendChild(item3Price);

  const title2 = document.createElement("h3");
  title2.classList.add("title2");
  title2.textContent = "Maki";
  menuList.appendChild(title2);
  const item4 = document.createElement("div");
  item4.classList.add("item4");
  menuList.appendChild(item4);
  const item4Title = document.createElement("h4");
  item4Title.classList.add("item4Title");
  item4Title.textContent = "California Roll";
  item4.appendChild(item4Title);
  const item4Desc = document.createElement("p");
  item4Desc.classList.add("item4Desc");
  item4Desc.textContent = "Crab, Cucumber, and Salmon.";
  item4.appendChild(item4Desc);
  const item4Price = document.createElement("p");
  item4Price.classList.add("item4Price");
  item4Price.textContent = "$8.50";
  item4.appendChild(item4Price);
  const item5 = document.createElement("div");
  item5.classList.add("item5");
  menuList.appendChild(item5);
  const item5Title = document.createElement("h4");
  item5Title.classList.add("item5Title");
  item5Title.textContent = "Seattle Roll";
  item5.appendChild(item5Title);
  const item5Desc = document.createElement("p");
  item5Desc.classList.add("item5Desc");
  item5Desc.textContent = "Avocado, Cucumber, and Salmon.";
  item5.appendChild(item5Desc);
  const item5Price = document.createElement("p");
  item5Price.classList.add("item5Price");
  item5Price.textContent = "$9.50";
  item5.appendChild(item5Price);
  const item6 = document.createElement("div");
  item6.classList.add("item6");
  menuList.appendChild(item6);
  const item6Title = document.createElement("h4");
  item6Title.classList.add("item6Title");
  item6Title.textContent = "Alaska Roll";
  item6.appendChild(item6Title);
  const item6Desc = document.createElement("p");
  item6Desc.classList.add("item6Desc");
  item6Desc.textContent = "Another State Named Roll.";
  item6.appendChild(item6Desc);
  const item6Price = document.createElement("p");
  item6Price.classList.add("item6Price");
  item6Price.textContent = "$11.50";
  item6.appendChild(item6Price);
}
